server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
    relabel_configs:
      - source_labels: [__meta_docker_container_name]
        target_label: service_name
        regex: "/(.*)"
        replacement: "$1"
    pipeline_stages:
      - json:
          expressions:
            log: log
            stream: stream
            docker_time: time
      - json:
          expressions:
            time: time
            level: level
            msg: msg
            source: source
          source: log
      - labels:
          level:
          msg:
          service_name: