global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'user-service'
    static_configs:
      - targets: ['pinstack-user-service:9101']

  - job_name: 'auth-service'
    static_configs:
      - targets: ['pinstack-auth-service:9102']

  - job_name: 'post-service'
    static_configs:
      - targets: ['pinstack-post-service:9103']

  - job_name: 'relation-service'
    static_configs:
      - targets: ['pinstack-relation-service:9104']

  - job_name: 'notification-service'
    static_configs:
      - targets: ['pinstack-notification-service:9105']

  - job_name: 'api-gateway'
    static_configs:
      - targets: ['pinstack-api-gateway:9106']